const UNAUTHORIZED_USER_REDIRECT_URL = "/login";
const REDIRECT_AFTER_LOGOUT_URL = "/login";

const CONNECTED_STATUS_READY = "ready";
const CODE_STATUS_PENDING = "pending";

export {
  CONNECTED_STATUS_READY,
  CODE_STATUS_PENDING,
  UNAUTHORIZED_USER_REDIRECT_URL,
  REDIRECT_AFTER_LOGOUT_URL,
};
